name: Build and deploy to aliyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: use Node.js 13.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0
      - name: Setup Hexo Dependencies
        run: |
            npm install hexo-cli -g
            npm install
      - name: Setup Deploy Private Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "39.100.253.134" >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh carr@39.100.253.134
          cd /home/carr/www
          git remote add origin https://github.com/lzjdp/blog.git
          git pull origin master
          git remote remove origin
      - name: delete ssh key
        run: rm -rf ~/.ssh/id_rsa
      # - name: Setup Git Infomation
      #   run: |
      #     git config --global user.name 'carr' 
      #     git config --global user.email 'carrlu@163.com'
      # - name: DeployHexo     
      #   run: |
      #     hexo clean
      #     hexo generate 
      #     hexo deploy
